resources:
  - name: myGitrepo
    type: gitRepo
    integration: github-manishas
    versionTemplate:     
      sourceName: devops-recipes/build_alpine_ci_image
      branch: master
    buildOnCommit: true
    buildOnTagPush: true

  - name: myEnv
    type: params
    versionTemplate:
      params:
        username: tbd
        password: tbd

jobs:
  - name: use_custom_image
    type: runSh
    steps:
      - IN: myGitrepo    # Configuring this as IN automatically logs you into your Docker registry
        switch: off
      - TASK:
          name: build_custom_image
          script:
            - pushd $(shipctl get_resource_state "myGitrepo")
            - docker build -t=devopsrecipes/build_alpine_ci -f Dockerfile.alpine37 --pull .
            - popd
      - TASK:
          name: need_to_use_custom_container
          runtime:
            options:
              imageName: devopsrecipes/build_alpine_ci    # Your image
              imageTag: latest                            # Your image tag  
              pull: false                                 # We already pulled image
              options: --dns=4.4.4.4 --dns=8.8.8.8        # This is optional
          script:
            - echo "Checking runtime values"              # Commands will run in container
            - sudo docker info    

  - name: write_to_params
    type: runSh
    steps:
      - OUT: myEnv
      - TASK:
          runtime:                  
            options:
              env:                  
                - secure: tBAG0ovnUdTQUxCNS8x4KDJsihaEc7sTMiJsJ/hQBaqNpqHKfot6JzNEHKvZvWC33iBTrb52eQbiGnj1RJMItpx+aZ1kUr0MR4HD3xLSnLOljb3G4Sc/3njkJ5T5/XFn4CI1gb2QpTLZQx45RaWC8KCKhsViavKFhN5krDnMdjS6zIoukYj9iKcY014oYx3BpU8KAG1cKANuzA8vDLPUMagDMHi2CNcOGjOu6iIjNYyOxP3GhqsgDKFBUnjvWTCCswXzy/lirOxJiMfgIunSFHr2+Vc7hXnCP+j/mXzhSRkh4IHPe+6PqM1t1E4hhguqrwdrUnHfV6IvMlceC/EZ5g== 
          script:
            - shipctl put_resource_state_multi "myEnv" "username=admin password=admin123"
            - echo $MYTEST
        
  - name: read_from_params
    type: runSh
    steps:
      - IN: myEnv
      - TASK:
          script:
            - echo $username
            - echo $password        
